# Generated by Django 2.2.4 on 2019-09-30 10:32

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='название')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DayQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True)),
                ('question', models.TextField(blank=True, null=True, verbose_name='вопрос')),
                ('answer_a', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_а')),
                ('answer_b', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_б')),
                ('answer_c', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_в')),
                ('answer_d', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_г')),
                ('answer_e', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_д')),
                ('true_answer', models.CharField(max_length=1, verbose_name='правильный ответ')),
                ('date', models.DateField(verbose_name='дата')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='время одного вопроса')),
            ],
            options={
                'verbose_name': 'Каждодневный вопрос',
                'verbose_name_plural': 'Каждодневные вопросы',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Дуэль',
                'verbose_name_plural': 'Дуэли',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.CharField(max_length=50, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Инфо',
                'verbose_name_plural': 'Инфо',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.CharField(max_length=50, verbose_name='Информация')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_to, verbose_name='аватар')),
            ],
            options={
                'verbose_name': 'Вуз',
                'verbose_name_plural': 'Вузы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='логин')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='пароль')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_to, verbose_name='аватар')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место проживания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='название')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='app.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='рейтинг')),
                ('created_at', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.Users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'рейтинг',
                'verbose_name_plural': 'рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True, verbose_name='вопрос')),
                ('answer_a', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_а')),
                ('answer_b', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_б')),
                ('answer_c', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_в')),
                ('answer_d', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_г')),
                ('answer_e', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_д')),
                ('true_answer', models.CharField(max_length=1, verbose_name='правильный ответ')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='время одного вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='app.Test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='GameQuizGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=100)),
                ('owner_point', models.IntegerField(verbose_name='рейтинг создателя')),
                ('outer_point', models.IntegerField(verbose_name='рейтинг')),
                ('user_outer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_outer', to='app.Users', verbose_name='Тот Кто принял')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to='app.Users', verbose_name='Тот Кто отправил')),
            ],
            options={
                'verbose_name': 'Тест для Дуэли',
                'verbose_name_plural': 'Тесты для Дуэли',
            },
        ),
        migrations.CreateModel(
            name='GameQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='вопрос')),
                ('answer_a', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_а')),
                ('answer_b', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_б')),
                ('answer_c', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_в')),
                ('answer_d', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_г')),
                ('answer_e', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ_д')),
                ('true_answer', models.CharField(max_length=1, verbose_name='правильный ответ')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='время одного вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='app.Game', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Тест для Дуэли',
                'verbose_name_plural': 'Тесты для Дуэли',
            },
        ),
    ]
