# Generated by Django 2.2.4 on 2019-09-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='название')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Главная Категория',
                'verbose_name_plural': 'Главные Категории',
            },
        ),
        migrations.AlterField(
            model_name='info',
            name='desc',
            field=models.CharField(max_length=1000, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='university',
            name='desc',
            field=models.CharField(max_length=1000, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.MainCategory', verbose_name='главная категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='app.MainCategory', verbose_name='главная категория'),
            preserve_default=False,
        ),
    ]
