# Generated by Django 2.2.4 on 2019-10-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191005_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitysubcategory',
            name='lang',
        ),
    ]
