# Generated by Django 2.2.4 on 2019-10-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_universitysubcategory_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('desc', models.CharField(max_length=1000, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='ORT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подготовка к ОРТ',
                'verbose_name_plural': 'Подготовка к ОРТ',
            },
        ),
        migrations.CreateModel(
            name='ORTDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('desc', models.CharField(max_length=1000, verbose_name='Информация')),
                ('ort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='app.ORT', verbose_name='Орт')),
            ],
            options={
                'verbose_name': 'описание',
                'verbose_name_plural': 'описание',
            },
        ),
    ]
