# Generated by Django 2.2.4 on 2019-10-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='false_answer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='true_answer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
