# Generated by Django 2.2.4 on 2019-10-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_kg',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_ru',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
