# Generated by Django 2.2.4 on 2019-10-27 11:12

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191027_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_to, verbose_name='логотип'),
        ),
    ]
