# Generated by Django 2.2.4 on 2019-11-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
        ('app', '0013_auto_20191101_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('fcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fcm_django.FCMDevice')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.Users')),
            ],
            options={
                'verbose_name': 'FCM device',
                'abstract': False,
            },
            bases=('fcm_django.fcmdevice',),
        ),
    ]
