# Generated by Django 2.2.4 on 2019-11-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='app.Users'),
        ),
    ]
