# Generated by Django 2.2.4 on 2019-11-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191104_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_view',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
