# Generated by Django 2.2.4 on 2019-11-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_notification_is_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not1', to='app.GameQuizGame'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
