# Generated by Django 2.2.4 on 2019-11-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191105_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='dayquiz',
            name='answer_a',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_а'),
        ),
        migrations.AlterField(
            model_name='dayquiz',
            name='answer_b',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_б'),
        ),
        migrations.AlterField(
            model_name='dayquiz',
            name='answer_c',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_в'),
        ),
        migrations.AlterField(
            model_name='dayquiz',
            name='answer_d',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_г'),
        ),
        migrations.AlterField(
            model_name='dayquiz',
            name='answer_e',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_д'),
        ),
        migrations.AlterField(
            model_name='dayquiz',
            name='true_answer',
            field=models.TextField(max_length=1, verbose_name='правильный ответ'),
        ),
        migrations.AlterField(
            model_name='gamequiz',
            name='answer_a',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_а'),
        ),
        migrations.AlterField(
            model_name='gamequiz',
            name='answer_b',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_б'),
        ),
        migrations.AlterField(
            model_name='gamequiz',
            name='answer_c',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_в'),
        ),
        migrations.AlterField(
            model_name='gamequiz',
            name='answer_d',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_г'),
        ),
        migrations.AlterField(
            model_name='gamequiz',
            name='answer_e',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_д'),
        ),
        migrations.AlterField(
            model_name='gamequizgame',
            name='quiz',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='desc',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ort',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ortdesc',
            name='desc',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='ortdesc',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_a',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_а'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_b',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_б'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_c',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_в'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_d',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_г'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_e',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='ответ_д'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='test',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='university',
            name='desc',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='universitysubcategory',
            name='desc',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='universitysubcategory',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
