# Generated by Django 2.2.4 on 2019-11-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191107_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='duel_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
