# Generated by Django 2.2.4 on 2019-11-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_notification_created_at'),
    ]


