# Generated by Django 2.2.4 on 2019-11-09 12:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
