# Generated by Django 2.2.4 on 2019-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191109_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
