# Generated by Django 2.2.4 on 2019-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20191110_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
