# Generated by Django 2.2.4 on 2019-11-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191110_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer_e',
            field=models.TextField(blank=True, null=True, verbose_name='ответ_д'),
        ),
    ]
