# Generated by Django 2.2.4 on 2019-11-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequizgame',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
