# Generated by Django 2.2.4 on 2019-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20191117_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_notification',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
