# Generated by Django 2.2.4 on 2019-11-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_users_is_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ortdesc',
            options={'verbose_name': 'Подготовка к ОРТ описание', 'verbose_name_plural': 'Подготовка к ОРТ описание'},
        ),
    ]
