# Generated by Django 2.2.4 on 2019-12-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20191123_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='lang',
            field=models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True),
        ),
    ]
