# Generated by Django 2.2.4 on 2020-01-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200119_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CommentQuestion'),
        ),
    ]
