# Generated by Django 2.2.4 on 2020-01-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_commentquestion_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentquestion',
            name='parent',
        ),
        migrations.CreateModel(
            name='AnswerToComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.CommentQuestion')),
            ],
            options={
                'verbose_name': 'Ответ к коментарию к задаче дня',
                'verbose_name_plural': 'Ответы к коментарию к задаче дня',
            },
        ),
    ]
