# Generated by Django 2.2.4 on 2020-01-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200119_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertocomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.Users'),
        ),
        migrations.AddField(
            model_name='commentquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='app.Users'),
        ),
    ]
