# Generated by Django 2.2.4 on 2020-01-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_likequiz_unlikequiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='likequiz',
            name='is_like',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.DeleteModel(
            name='UnLikeQuiz',
        ),
    ]
