# Generated by Django 2.2.4 on 2020-01-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200120_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likequiz',
            name='answer',
        ),
        migrations.CreateModel(
            name='LikeAnswerQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Like'), (2, 'UnLike')], null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_answer_quiz', to='app.AnswerToComment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_answer_quiz', to='app.Users')),
            ],
        ),
    ]
