# Generated by Django 2.2.4 on 2020-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='draw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='lose',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
