# Generated by Django 2.2.4 on 2020-03-01 21:33

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20200225_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerToCommentForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Ответ к коментарию к Форуму',
                'verbose_name_plural': 'Ответы к коментарию к Форуму',
            },
        ),
        migrations.CreateModel(
            name='CommentForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.DayQuiz')),
            ],
            options={
                'verbose_name': 'Коментарий к Форуму',
                'verbose_name_plural': 'Коментарии к Форуму',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Название форума',
                'verbose_name_plural': 'Название форума',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_to, verbose_name='картинка')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='app.Forum')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='app.Users')),
            ],
            options={
                'verbose_name': 'Тема форума',
                'verbose_name_plural': 'Тема форума',
            },
        ),
        migrations.CreateModel(
            name='LikeForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('like', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Like'), (2, 'UnLike')], null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_forum', to='app.CommentForum')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_forum', to='app.Users')),
            ],
        ),
        migrations.CreateModel(
            name='LikeAnswerForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('like', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Like'), (2, 'UnLike')], null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_answer_forum', to='app.AnswerToCommentForum')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_answer_forum', to='app.Users')),
            ],
        ),
        migrations.AddField(
            model_name='commentforum',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_forum', to='app.Users'),
        ),
        migrations.AddField(
            model_name='answertocommentforum',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.CommentForum'),
        ),
        migrations.AddField(
            model_name='answertocommentforum',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_forum', to='app.Users'),
        ),
    ]
