# Generated by Django 2.2.4 on 2020-03-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200302_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentforum',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.Topic'),
        ),
    ]
