# Generated by Django 2.2.4 on 2020-03-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200302_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='lang',
            field=models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True),
        ),
    ]
