# Generated by Django 2.2.4 on 2020-03-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_forum_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
