# Generated by Django 2.2.4 on 2020-03-08 09:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_topic_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_to, verbose_name='картинка'),
        ),
    ]
