# Generated by Django 2.2.4 on 2020-03-10 09:10

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_forum_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_to, verbose_name='картинка')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True)),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic1', to='app.Forum')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic1', to='app.Users')),
            ],
            options={
                'verbose_name': 'Тема форума',
                'verbose_name_plural': 'Тема форума',
            },
        ),
        migrations.AlterField(
            model_name='commentforum',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.Topic1'),
        ),
    ]
