# Generated by Django 2.2.4 on 2020-04-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20200310_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True)),
            ],
            options={
                'verbose_name': 'Название пробного теста',
                'verbose_name_plural': 'Названии пробного теста',
            },
        ),
        migrations.CreateModel(
            name='UnderstandOrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='вопрос')),
                ('answer_a', models.TextField(blank=True, null=True, verbose_name='ответ_а')),
                ('answer_b', models.TextField(blank=True, null=True, verbose_name='ответ_б')),
                ('answer_c', models.TextField(blank=True, null=True, verbose_name='ответ_в')),
                ('answer_d', models.TextField(blank=True, null=True, verbose_name='ответ_г')),
                ('answer_e', models.TextField(blank=True, null=True, verbose_name='ответ_д')),
                ('true_answer', models.CharField(max_length=1, verbose_name='правильный ответ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='understand', to='app.CategoryOrt', verbose_name='название пробного теста')),
            ],
            options={
                'verbose_name': 'Пробный тест (Чтение и понимание)',
                'verbose_name_plural': 'Пробные тесты (Чтение и понимание)',
            },
        ),
        migrations.CreateModel(
            name='PayOrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_used', models.BooleanField(blank=True, default=False, null=True, verbose_name='использовано?')),
                ('used_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='app.Users')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='Math2Ort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='вопрос')),
                ('answer_a', models.TextField(blank=True, null=True, verbose_name='ответ_а')),
                ('answer_b', models.TextField(blank=True, null=True, verbose_name='ответ_б')),
                ('answer_c', models.TextField(blank=True, null=True, verbose_name='ответ_в')),
                ('answer_d', models.TextField(blank=True, null=True, verbose_name='ответ_г')),
                ('answer_e', models.TextField(blank=True, null=True, verbose_name='ответ_д')),
                ('true_answer', models.CharField(max_length=1, verbose_name='правильный ответ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math2', to='app.CategoryOrt', verbose_name='название пробного теста')),
            ],
            options={
                'verbose_name': 'Пробный тест (Математика2)',
                'verbose_name_plural': 'Пробные тесты (Математика2)',
            },
        ),
        migrations.CreateModel(
            name='Math1Ort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='вопрос')),
                ('answer_a', models.TextField(blank=True, null=True, verbose_name='ответ_а')),
                ('answer_b', models.TextField(blank=True, null=True, verbose_name='ответ_б')),
                ('answer_c', models.TextField(blank=True, null=True, verbose_name='ответ_в')),
                ('answer_d', models.TextField(blank=True, null=True, verbose_name='ответ_г')),
                ('answer_e', models.TextField(blank=True, null=True, verbose_name='ответ_д')),
                ('true_answer', models.CharField(max_length=1, verbose_name='правильный ответ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math1', to='app.CategoryOrt', verbose_name='название пробного теста')),
            ],
            options={
                'verbose_name': 'Пробный тест (Математика1)',
                'verbose_name_plural': 'Пробные тесты (Математика1)',
            },
        ),
        migrations.CreateModel(
            name='GrammarOrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='вопрос')),
                ('answer_a', models.TextField(blank=True, null=True, verbose_name='ответ_а')),
                ('answer_b', models.TextField(blank=True, null=True, verbose_name='ответ_б')),
                ('answer_c', models.TextField(blank=True, null=True, verbose_name='ответ_в')),
                ('answer_d', models.TextField(blank=True, null=True, verbose_name='ответ_г')),
                ('answer_e', models.TextField(blank=True, null=True, verbose_name='ответ_д')),
                ('true_answer', models.CharField(max_length=1, verbose_name='правильный ответ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar', to='app.CategoryOrt', verbose_name='название пробного теста')),
            ],
            options={
                'verbose_name': 'Пробный тест (Грамматика)',
                'verbose_name_plural': 'Пробные тесты (Грамматика)',
            },
        ),
        migrations.CreateModel(
            name='AnalogOrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='вопрос')),
                ('answer_a', models.TextField(blank=True, null=True, verbose_name='ответ_а')),
                ('answer_b', models.TextField(blank=True, null=True, verbose_name='ответ_б')),
                ('answer_c', models.TextField(blank=True, null=True, verbose_name='ответ_в')),
                ('answer_d', models.TextField(blank=True, null=True, verbose_name='ответ_г')),
                ('answer_e', models.TextField(blank=True, null=True, verbose_name='ответ_д')),
                ('true_answer', models.CharField(max_length=1, verbose_name='правильный ответ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog', to='app.CategoryOrt', verbose_name='название пробного теста')),
            ],
            options={
                'verbose_name': 'Пробный тест (Аналогии)',
                'verbose_name_plural': 'Пробные тесты (Аналогии)',
            },
        ),
    ]
