# Generated by Django 2.2.4 on 2020-04-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_pointsort'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescOrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.IntegerField(blank=True, choices=[(1, 'KG'), (2, 'RU')], null=True)),
                ('category', models.IntegerField(blank=True, choices=[(0, 'Математика 1'), (1, 'Математика 2'), (2, 'Аналогия'), (3, 'Чтение и понимание'), (4, 'Грамматика'), (5, 'Общее')], null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Информация об Орт',
                'verbose_name_plural': 'Информации об Орт',
            },
        ),
        migrations.AlterModelOptions(
            name='pointsort',
            options={'verbose_name': 'Балл пробного теста', 'verbose_name_plural': 'Баллы пробного теста'},
        ),
    ]
