# Generated by Django 2.2.4 on 2020-04-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20200426_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math1ort',
            options={'verbose_name': 'Пробный тест', 'verbose_name_plural': 'Пробные тесты'},
        ),
        migrations.AddField(
            model_name='math1ort',
            name='type_of_test',
            field=models.IntegerField(blank=True, choices=[(0, 'Математика 1'), (1, 'Математика 2'), (2, 'Аналогия'), (3, 'Чтение и понимание'), (4, 'Грамматика')], null=True),
        ),
    ]
