# Generated by Django 2.2.4 on 2020-06-07 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20200606_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsort',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ort', to='app.CategoryOrt'),
        ),
    ]
